- hosts: localhost
  tasks:
  
    - name: Get repository
      git:
       repo: 'https://github.com/toharikr/devopsazuredemo.git'
       dest: $(Build.SourcesDirectory)    
    
    - name: ansible create directory example
      file:
       path: ~/.azure
       state: directory
    - copy:
       src: $(Build.SourcesDirectory)/credentials
       dest: ~/.azure
       
    - local_action:
        command ansible-galaxy install toharikr.aks
        
    - include_role:
        name: toharikr.aks
      vars:
        monitoring: yes
        name: akscluster
        resource_group: aksroletest
