- hosts: localhost
  tasks:
  
      - name: install role
        command: ansible-galaxy install azure.aks
        
      - include_role:
           name: azure.aks
        vars:
           monitoring: yes
           name: akscluster
           resource_group: aksroletest
